### ISSUE TITLE
Install version 3.11 on Moodle 4.01 [Firts install] can't preview questions or take quizz, still offline

### ISSUE THREAD

**Issue by JZJeff** [ethz-let/moodle-quizaccess_wifiresilience#1]
Hello,

I'm trying to install for the first time your plugin (V3.11) on our test Moodle in 4.01.

We are interested in using your plugin since we have a Moodle with over 27'000 users.

I am aware that Moodle 3.11 and 4.01 are quite different and may cause technical problems. However, when installing it, no errors were reported!

I left the post-installation settings blank. I then went back to the "Quizz Wifi Resilience Mode" settings. Moodle had generated the private and public key.

From this step, I created the quiz activity and activated the Wifi Resilience Mode. I get the same screen as on the Moodle.org/plugins page. That is, the 2 yellow blocks.

However I cannot preview the questions or take the test because I am automatically redirected to the "You are Offline" page.

If I click on "Refresh Page", I stay on the same page (Offline)
If I click on "Download Exam Emergency File", a pop-up window opens "No Current Exam Emergency File. Either exam has been finished and submitted correctly, or there was no exam attempt at all". Then after clicking on Ok, I have second one : "Cant Generate emergency file"

Could you help me to determine if this is an error in the plugin settings, in the activity settings ? or if there have been changes due to version 4.01?

Thank you for your work and this plugin!

Jeff Zufferey
![SameCpature](https://user-images.githubusercontent.com/26893527/178961852-a151462d-ad60-4190-a1e0-7be2a5bb53fc.PNG)
![Offline Mode](https://user-images.githubusercontent.com/26893527/178961864-293399b6-41d5-4bd5-bde5-6cbb9bf6bf1b.PNG)

**Comment by nexterday** [comment]
Hi Jeff, sometimes this issue happen with browser has a malfunction (for example old ffx or IE), and first step is to clear browser cache and offline files then try again. Shall the issue persist, please send more details like console print and browser details, and would be cool if you can give me a temp editing teacher role in your environment for that specific quiz. Shall you want to proceed, pls send the access details privately to Thomas and he will forward it to me.

**Comment by JZJeff** [comment]
Hello Nexterday! 

I sent Thomas an access to our test server. 

I updated the 3.11 plugin to the latest 4.0 version from 14 days ago. Then clear the browser cache and offline files.

I couldn't see the field to create a token in the quiz configuration, but the plugin level filler works. 

Now it seems to work. I can load and see the questions in the preview. 
 
I'm going to continue my tests ! 

Your are free to connect at this moodle for test. 

I thank you for your help. 

Jeff Zufferey

**Comment by JZJeff** [comment]
Hola I have one last problem it seems. 

I can only create a token in the plugin settings and not in the quiz settings. 

it's working with plugin level setting, the corresponding field in the quiz settings is missing...  

Could you help me? 

Jeff Zufferey

![image_2022-07-15_155059](https://user-images.githubusercontent.com/26893527/179236770-8125fa10-7fbd-4e07-bffc-5bc6579fab76.png)
![image_2022-07-15_155123](https://user-images.githubusercontent.com/26893527/179236852-47031c63-670f-4f7f-b6c7-cc27002aaf14.png)
![image_2022-07-15_155144](https://user-images.githubusercontent.com/26893527/179236903-1ae6e49a-8891-4217-94e8-413414b83a47.png)

**Comment by nexterday** [comment]
Hi Jeff, we disabled the field on purpose to prevent users from over-creating or overusing them, and mainly because when token has expired or changed, old quizes might still have the stale token and gone unnoticed. Background sync now applies to “one stop shop” and for all quizes that have wifi plugin enabled for.
