### ISSUE TITLE
Specific branch MOODLE_401_STABLE doesn't work: wrong class names

### ISSUE THREAD

**Issue by moodleulpgc** [ethz-let/moodle-quizaccess_wifiresilience#5]
plugin version 4.4 is the latest available and  declared "Latest release for Moodle 4.1".
But  current version 4.4 of the plugin is NOT compatible with moodle 4.1 LTS.   

You have a branch for MOODLE_401_STABLE that should be compatible with moodle 4.1 LTS. But you have updated that specific branch, too, with features non-existent in moodle 4.1. 
For instance, checking out specifically branch   MOODLE_401_STABLE  or your plugin,  the code in rula.php  try to use classes like  
```
 use mod_quiz\local\access_rule_base;
 use mod_quiz\quiz_settings;
```
Those classes don't exist in moodle 4.1 (MOODLE_401_STABLE) that versions relies on `mod/quiz/accessrule/accessrulebase.php` yet 
And quiz_settings are in quizobj

The code try to use features only available in moodle 4.2 or 4.3, so you get a fatal error if you install this updated 4.4 version of the plugin in moodle 4.1.  
With the undesired side effect that you cannot use the quiz module at all, because on entering the main quiz page the system checks for available accessrules and this one generates a fatal error, aborting loading of quiz entry page.

**Comment by nexterday** [comment]
please stop duplicating and writing the same issue on every environment.
